config/routes.rb
Geneatree::Application.routes.draw do
  devise_for :users
  
  resources :trees do 
    member do
      get :render_tree
    end
    resources :individuals do
      member do
        get :add_connection
      end
    end
  end
  
  resources :individuals 
      
  get "trees/index"

  root 'welcome#index'

  

end

app/models/individual.rb
class Individual < ActiveRecord::Base
  belongs_to :tree
  
  belongs_to :parent_a, class_name: "Individual", foreign_key: "parent_a_id"
  belongs_to :parent_b, class_name: "Individual", foreign_key: "parent_b_id"
  has_one :spouse, class_name: "Individual", foreign_key: "spouse_id"
  
  has_many :children, class_name: "Individual"
  has_many :siblings, class_name: "Individual"
  
  def children
    Individual.where("parent_a_id = ? OR parent_b_id = ?", id, id)
  end
  
  def siblings
    Individual.where("parent_a_id = ?", parent_a_id) - [Individual.find(id)]
  end
  
  def update_child_with_new_parent(parent)
    parent.generation = self.generation + 1
    if self.parent_a.nil?
      self.parent_a = parent
      parent.direct = true
      parent.save
    else
      self.parent_b = parent
      self.parent_a.spouse = parent
      parent.spouse = self.parent_a
      if parent.spouse.direct and parent.generation > 0
        parent.direct = true
      else
        parent.direct = false
      end
      parent.save
      self.parent_a.save
    end
    self.save
  end
  
  def update_new_child(child)
    child.generation = self.generation - 1
    child.parent_a = self
    child.parent_b = self.spouse if self.spouse.present?
    if child.generation < 0 and (self.direct or self.spouse.direct)
      child.direct = true
    else
      child.direct = false
    end
    child.save
  end
  
end

app/models/tree.rb
class Tree < ActiveRecord::Base
  belongs_to :user
  has_many :individuals
  
  def individuals_ordered
    progen = self.individuals.min_by(&:id)
    io = []
    
    io.push(*progen.siblings) if progen.siblings.present?
    io.push(progen)
    io.push(progen.spouse) if progen.spouse.present?
    recursive_add_ancestors(progen, io)
    recursive_add_descendents(progen.children, io)
    
    spouses_arr = []
    io.each do |i|
      if i.spouse.present? and !spouses_arr.include?(i)
        spouses_arr.push(i.spouse)
      end
    end
    return io - spouses_arr
  end
  
  def recursive_add_ancestors (child, io_array)
    if child.present?
      if child.parent_a.present?
        io_array.push(*child.parent_a.siblings) if child.parent_a.siblings.present?
        io_array.push(child.parent_a)
      end
      if child.parent_b.present?
        io_array.push(child.parent_b)
        io_array.push(*child.parent_b.siblings) if child.parent_b.siblings.present?
      end
    recursive_add_ancestors(child.parent_a, io_array)
    recursive_add_ancestors(child.parent_b, io_array)
    end
  end
  
  def recursive_add_descendents (children_array, io_array)
    if !children_array.empty?
      next_gen_array = []
      children_array.each do |c|
        io_array.push(c)
        io_array.push(c.spouse) if c.spouse.present?
        next_gen_array.push(*c.children)
      end
      recursive_add_descendents(next_gen_array, io_array)
    end
  end  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :trees
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  before_action :set_individual, only: [:update, :destroy]
  before_action :set_tree, only: [:create, :update]
  def new
  end
  
  def create
    @individual = @tree.individuals.create(individual_params)
    
    if @tree.individuals.count == 1
      @individual.generation = 0
      @individual.blood = true
      @individual.direct = true
      @individual.save!
    end
    
    if params[:connection_type].present?
      @connected = Individual.find(params[:connected_id])
      if params[:connection_type] == "1"
        @connected.update_child_with_new_parent(@individual)
      elsif params[:connection_type] == "2"
        @connected.update_new_child(@individual)
      end
    end
    
    if @tree.oldest_gen <= @individual.generation
      @tree.update_attribute(:oldest_gen, @individual.generation)
    end    
    redirect_to tree_path(@tree)
  end
  
  def add_connection
    @individual = Individual.new
    @pass = params
    
    respond_to do |format|  
      format.html
      format.js
    end
  end
  
  def update
    @individual.update(individual_params)
    redirect_to tree_path(@tree)
  end
  
  def destroy
    @individual.destroy
    respond_to do |format|
      format.html { redirect_to tree_path(@tree) }
      format.json { head :no_content }
    end
  end
  
  private
  
    def set_tree
      @tree = Tree.find(params[:tree_id])
    end
  
    def set_individual
      @individual = Individual.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def individual_params
      params.require(:individual).permit(:name)
    end  
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy, :render_tree]
  before_filter :authenticate_user!

  # GET /trees
  # GET /trees.json
  def index
    @user = current_user
    @trees = @user.trees
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
    @ind_ordered = @tree.individuals_ordered if @tree.individuals.present?
    respond_to do |format|  
      format.html
      format.js
    end
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)
    @tree.user = current_user
    @tree.oldest_gen = 0

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tree }
      else
        format.html { render action: 'new' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url }
      format.json { head :no_content }
    end
  end
  
  def form
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def render_tree
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.require(:tree).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/individuals/_add_connection.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">
      	<% if @pass[:connection_type] == "1"%>
					Add parent
				<% else %>
					Add child
				<% end %>
      </h4>
    </div>
    <div class="modal-body">
			
			<%= form_for @individual do |f| %>
				<%= hidden_field_tag :tree_id, @pass[:tree_id] %>
				<%= hidden_field_tag :connected_id, @pass[:id] %>
				<%= hidden_field_tag :connection_type, @pass[:connection_type] %>

			  <div class="control-group">
			    <%= f.label :name, :class => 'control-label' %>
			    <div class="controls">
			      <%= f.text_field :name, :class => 'text_field' %>
			    </div>
			  </div>
			  <div class="form-actions">
			    <%= f.submit nil, :class => 'btn btn-primary' %>
			  </div>
			<% end %>
      
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="button" class="btn btn-primary">Save changes</button>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/individuals/add_connection.js.erb
$("#modal-window").html("<%= escape_javascript(render partial: 'individuals/add_connection') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Geneatree" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
		<script src="http://d3js.org/d3.v3.min.js"></script>
		<script src="http://cpettitt.github.io/project/dagre-d3/latest/dagre-d3.min.js"></script>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
		<%= link_to "Geneatree", root_path, class: "brand" %>
        <div class="container nav-collapse">
			<ul class="nav">
				<li>
					<%= link_to "Trees", trees_path %>
				</li>
			</ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>
					<li>
						<p class="navbar-text">
							<%= "Welcome, #{current_user.email}!" %>
						</p>
					</li>
					<%= link_to "Logout", destroy_user_session_path, class: "btn btn-default navbar-btn", method: "delete" %>
				<% else %>
					<%= link_to "Login", new_user_session_path, class: "btn btn-default navbar-btn" %>
				<% end %>
			</ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

app/views/trees/_form.html.erb
<%= form_for @tree, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                trees_path, :class => 'btn' %>
  </div>
<% end %>

app/views/trees/_render_tree.html.erb
<script>
	var g = new dagreD3.Digraph();
	<% @ind_ordered.each do |i| %>
		g.addNode("<%= i.id %>", {label: "<div style='padding:10px' class='name'><%= i.name %></div><div style='padding: 5px 0px 10px 0px;min-width:130px;width:100%' class='node-footer' id='<%= i.id %>'><span>&nbsp;</span></div>"});
		<% if i.spouse.present? %>
			g.addNode("<%= i.spouse.id %>", {label: "<div style='padding:10px' class='name'><%= i.spouse.name %></div><div style='padding: 5px 0px 10px 0px;min-width:130px;width:100%' class='node-footer' id='<%= i.spouse.id %>'><span>&nbsp;</span></div>" });
			g.addNode("marriage<%= "#{i.id}-#{i.spouse.id}" %>", {class: "marriage"});		
		<% elsif i.children.present? %>
			g.addNode("nonmarriage<%= i.id %>", {class: "marriage"});
		<% end %>
	<% end %>

	<% @ind_ordered.each do |i| %>
		<% if i.spouse.present? %>
			g.addEdge(null, "<%= i.id %>", "marriage<%= "#{i.id}-#{i.spouse.id}" %>");
			g.addEdge(null, "<%= i.spouse.id %>", "marriage<%= "#{i.id}-#{i.spouse.id}" %>");
			<% i.children.each do |c| %>
				g.addEdge(null, "marriage<%= "#{i.id}-#{i.spouse.id}" %>", "<%= c.id %>");
			<% end %>
		<% elsif i.children.present? %>
			g.addEdge(null, "<%= i.id %>", "nonmarriage<%= i.id %>");
			<% i.children.each do |c| %>
				g.addEdge(null, "nonmarriage<%= i.id %>", "<%= c.id %>");
			<% end %>
		<% end %>
	<% end %>
	var renderer = new dagreD3.Renderer();
	var oldDrawNodes = renderer.drawNodes();

	renderer.drawNodes(function(graph, svg) {
	  var svgNodes = oldDrawNodes(graph, svg);
	  svgNodes.select("rect").attr("class", function(u) { return graph.node(u).class; });
		return svgNodes;
	});

	// Overriding the default edge path function to not use arrowheads...
	renderer.drawEdgePaths(function(g, root) {
	  var svgEdgePaths = root
	    .selectAll('g.edgePath')
	    .classed('enter', false)
	    .data(g.edges(), function(e) { return e; });

	  svgEdgePaths
	    .enter()
	      .append('g')
	        .attr('class', 'edgePath enter')
	        .append('path')
	          .style('opacity', 0)

	  this._transition(svgEdgePaths.exit())
	      .style('opacity', 0)
	      .remove();

	  return svgEdgePaths;
	});
	renderer.edgeInterpolate("step-after");

	renderer.run(g, d3.select("svg g"));
	
	<% @tree.individuals.each do |i| %>
		
		var button_group_<%= i.id %> = '<% if i.direct %>Add:<% if (i.parent_a.nil? or i.parent_b.nil?) %><%= link_to('Parent', add_connection_tree_individual_path(:id => i.id, :tree_id => @tree.id, :connection_type => "1"), remote: true, class: "btn btn-mini", 'data-toggle' => "modal", 'data-target' => "#modal-window") %><% end %>\
		<%= link_to('Child', add_connection_tree_individual_path(:id => i.id, :tree_id => @tree.id, :connection_type => "2"), remote: true, class: "btn btn-mini", 'data-toggle' => "modal", 'data-target' => "#modal-window") %><% end %>';
		$('#<%= i.id %> span').append(button_group_<%= i.id %>);
	<% end %>
</script>

app/views/trees/edit.html.erb
<%- model_class = Tree -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trees/index.html.erb
<%- model_class = Tree -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<% if @trees.count == 0 %>
  <p>You don't have any trees yet. Hit the button below to make a new one!</p>
<% else %>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th><%= model_class.human_attribute_name(:id) %></th>
	      <th><%= model_class.human_attribute_name(:title) %></th>
	      <th><%= model_class.human_attribute_name(:user_id) %></th>
	      <th><%= model_class.human_attribute_name(:created_at) %></th>
	      <th><%=t '.actions', :default => t("helpers.actions") %></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @trees.each do |tree| %>
	      <tr>
	        <td><%= link_to tree.id, tree_path(tree) %></td>
	        <td><%= tree.title %></td>
	        <td><%= tree.user.email %></td>
	        <td><%=l tree.created_at %></td>
	        <td>
	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
	                      edit_tree_path(tree), :class => 'btn btn-mini' %>
	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                      tree_path(tree),
	                      :method => :delete,
	                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                      :class => 'btn btn-mini btn-danger' %>
	        </td>
	      </tr>
	    <% end %>
	<% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tree_path,
            :class => 'btn btn-primary' %>

app/views/trees/new.html.erb
<%- model_class = Tree -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trees/show.html.erb
<%- model_class = Tree -%>
<div class="page-header">
  <h1><%= @tree.title %></h1>
</div>

<% if @tree.individuals.empty? %>

	<div>
		Add the first person to your tree to start off:
		<%= form_for([@tree,@tree.individuals.build]) do |f| %>
			<div class="form-group">
			  <%= f.label "Name", class: 'control-label' %>
			  <%= f.text_field :name, class: 'form-control' %>
			</div>
			<div class="form-group">
			  <%= f.submit "Submit", class: 'btn btn-default' %>
			</div>
		<% end %>
	</div>

<% else %>
	<div id="svgholder">
		<svg>
			<g transform="translate(20,20)"/>
		</svg>
	</div>
	<%= render partial: "trees/render_tree" %>

	<script>
	$(window).on("load", function(){
	    var gwidth = $('g')[0].getBBox().width;
		var gheight = $('g')[0].getBBox().height;
		$('svg').width(gwidth+40);
		$('svg').height(gheight+40);
	});
	</script>
<% end %>

<!-- Modal -->
<div id="modal-window" class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div><!-- /.modal -->

app/views/welcome/index.html.erb
<div class="row">
	<div class="span8 offset2">
		<div class="page-header">
		  <h1>Geneatree <small>Easily create family trees</small></h1>
		</div>
		<p>Geneatree is a lightweight application that allows the creation of family trees. It creates the trees using a Javascript library for directed graphs, Dagre. Right now there are some limitations on who can be added to the tree, so as to avoid overlapping lines.</p>
		<strong>Who can be added to the tree?</strong>
		<ul>
			<li>The starting individual</li>
			<li>Direct ancestors of the starting individual (parents, grandparents, great-grandparents, etc.) and their children</li>
			<li>Direct descendents of the starting individual (children, grandchildren, etc.) and their parents</li>
		</ul>
	</div>
</div>